stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker-compose build
    - docker-compose push
  only:
    - main

deploy:
  stage: deploy
  image: 
    name: hashicorp/terraform:light
    entrypoint: [""]
  before_script:
    - cd terraform
    - terraform init
  script:
    - terraform apply -auto-approve
  only:
    - main
  environment:
    name: production